imports:
    - { resource: Events/services.yaml }
    - { resource: ../Utility/services.yaml }
    - { resource: ../Logger/services.yaml }
    - { resource: ../Common/services.yaml }
    - { resource: ../Review/services.yaml }
    - { resource: ../Form/services.yaml }
    - { resource: ../Adapter/services.yaml }
    - { resource: ../Configuration/Module/services.yaml }
    - { resource: ../Module/services.yaml }
